name = "sellitool"
compatibility_date = "2025-06-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "sellitool"
database_id = "8c3548d2-9876-44fd-8fc1-c9a72833e0e5"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "sellitool-photos"
